# Generated by Django 5.2.4 on 2025-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
